#!/usr/bin/env python3
"""Generate the documentation pages that are derived from the source tree.

Two things here are not written by hand:

* ``docs/api/*.md`` -- the API reference. It lists every public name a
  subpackage exports with its real signature and the first line of its
  docstring; 836 entries would drift the first time a default changed.
* ``docs/changelog.md`` -- a copy of the top-level ``CHANGELOG.md``, which
  MkDocs cannot read from outside its ``docs`` directory.

``tests/test_docs.py`` runs the check mode, so a stale page fails the suite.

Usage::

    python tools/gen_docs.py            # rewrite the generated pages
    python tools/gen_docs.py --check    # exit 1 if any page is stale
"""

from __future__ import annotations

import argparse
import inspect
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import quadrivium  # noqa: E402

DOCS_DIR = ROOT / "docs"
API_DIR = DOCS_DIR / "api"
CHANGELOG = ROOT / "CHANGELOG.md"

# Subpackage -> (title, one-line description used on the index page).
SUBPACKAGES = [
    ("core", "Core", "Result records, exceptions, norms, and shared numerical helpers"),
    ("linalg", "Linear algebra",
     "Factorizations, eigenvalues, Krylov solvers, least squares, sparse storage, "
     "matrix functions and equations, randomized methods"),
    ("rootfind", "Root finding",
     "Scalar equations, nonlinear systems, and polynomial roots"),
    ("interpolate", "Interpolation",
     "Polynomial, spline, rational, and multivariate interpolation"),
    ("approx", "Approximation",
     "Orthogonal polynomials, Gauss nodes, least squares, Pade, minimax, Fourier"),
    ("diff", "Differentiation",
     "Finite differences, automatic differentiation, spectral differentiation"),
    ("integrate", "Integration",
     "Newton-Cotes, Gauss, adaptive, Monte Carlo, oscillatory, singular, and "
     "multidimensional quadrature"),
    ("ode", "Ordinary differential equations",
     "One-step, multistep, symplectic, exponential, extrapolation, events, BVPs, "
     "DAEs, delay equations"),
    ("pde", "Partial differential equations",
     "Parabolic, hyperbolic, elliptic, multigrid, FEM, FVM, spectral, WENO, "
     "incompressible Navier-Stokes"),
    ("optimize", "Optimization",
     "Line searches, quasi-Newton, trust region, derivative-free, global, "
     "constrained, proximal, linear programming"),
    ("transforms", "Transforms",
     "DFT/FFT family, signal processing, wavelets"),
    ("stochastic", "Stochastic methods",
     "Random generation, sampling, MCMC, statistics, SDE solvers"),
    ("special", "Special functions",
     "Gamma, beta, error, Bessel, Airy, elliptic, hypergeometric, Lambert W, "
     "zeta, spherical harmonics"),
]

GUIDE_FOR = {name: f"../guides/{name}.md" for name, _, _ in SUBPACKAGES}

# Docstrings use a little Sphinx-flavoured markup; Markdown wants plain code.
RST_ROLE = re.compile(r":(mod|func|class|meth|attr|data|obj|ref):`([^`]+)`")

HEADER = (
    "<!-- Generated by tools/gen_docs.py. Do not edit by hand;\n"
    "     run `python tools/gen_docs.py` after changing the public API. -->\n"
)

CHANGELOG_HEADER = (
    "<!-- Generated by tools/gen_docs.py from CHANGELOG.md at the repository\n"
    "     root. Edit that file, then run `python tools/gen_docs.py`. -->\n"
)


def prose(text: str) -> str:
    """Collapse a docstring paragraph to one line of Markdown."""
    return RST_ROLE.sub(r"``\2``", " ".join(text.split()))


def first_line(obj) -> str:
    """Summary paragraph of an object's docstring, collapsed onto one line."""
    doc = inspect.getdoc(obj) or ""
    # A plain value (a constant, say) inherits its type's docstring, which
    # describes ``float``, not the constant. Show the value instead.
    if kind_of(obj) == "value" and doc == (inspect.getdoc(type(obj)) or ""):
        return f"`{obj!r}`"
    if not doc:
        return ""
    paragraph = doc.split("\n\n")[0]
    line = " ".join(part.strip() for part in paragraph.splitlines() if part.strip())
    line = prose(line)
    if len(line) > 200:  # keep the table scannable
        line = line[:197].rsplit(" ", 1)[0] + " ..."
    return line.replace("|", r"\|")


def signature_of(obj) -> str:
    """Rendered call signature, or an empty string when there is none to show."""
    target = obj
    if inspect.isclass(obj):
        init = getattr(obj, "__init__", None)
        dataclass_fields = getattr(obj, "__dataclass_fields__", None)
        if init is None and dataclass_fields is None:
            return "()"
        target = obj
    # ``from __future__ import annotations`` leaves annotations as strings;
    # resolving them renders ``tol: float`` rather than ``tol: 'float'``.
    try:
        sig_obj = inspect.signature(target, eval_str=True)
    except (TypeError, ValueError, NameError, AttributeError):
        try:
            sig_obj = inspect.signature(target)
        except (TypeError, ValueError):
            return ""
    sig = str(_name_callable_defaults(sig_obj))
    sig = " ".join(sig.split())
    if len(sig) > 110:
        sig = sig[:107].rstrip(", ") + ", ...)"
    return sig.replace("|", r"\|")


class _Named:
    """Stand-in whose ``repr`` is a bare name, for callable default values."""

    def __init__(self, name: str) -> None:
        self._name = name

    def __repr__(self) -> str:
        return self._name


def _name_callable_defaults(sig: inspect.Signature) -> inspect.Signature:
    """Render ``method=brent`` instead of ``method=<function brent at 0x...>``.

    The address in the default repr changes every run, which would make the
    generated pages differ from one another for no reason.
    """
    params = []
    for param in sig.parameters.values():
        default = param.default
        if default is not inspect.Parameter.empty and callable(default):
            name = getattr(default, "__name__", None)
            if name:
                param = param.replace(default=_Named(name))
        params.append(param)
    return sig.replace(parameters=params)


def kind_of(obj) -> str:
    if inspect.isclass(obj):
        return "class"
    if inspect.isfunction(obj) or inspect.isbuiltin(obj):
        return "function"
    return "value"


def origin_of(package, package_name: str, name: str, obj) -> str:
    """Module a name comes from, including for constants with no ``__module__``."""
    module_name = getattr(obj, "__module__", None)
    if module_name:
        return module_name
    prefix = f"quadrivium.{package_name}."
    for candidate, module in sorted(sys.modules.items()):
        if not candidate.startswith(prefix):
            continue
        if name in getattr(module, "__all__", []) and getattr(module, name, None) is obj:
            return candidate
    return f"quadrivium.{package_name}"


def module_entries(package_name: str):
    """Public names of a subpackage, grouped by the module that defines them."""
    package = getattr(quadrivium, package_name)
    exported = [n for n in getattr(package, "__all__", [])
                if not inspect.ismodule(getattr(package, n, None))]
    groups: dict[str, list[str]] = {}
    for name in exported:
        obj = getattr(package, name, None)
        if obj is None:
            continue
        groups.setdefault(origin_of(package, package_name, name, obj), []).append(name)

    ordered = []
    for module_name in sorted(groups, key=lambda m: (not m.startswith(
            f"quadrivium.{package_name}"), m)):
        try:
            module = sys.modules[module_name]
        except KeyError:  # pragma: no cover - every origin is imported already
            continue
        names = groups[module_name]
        authored = [n for n in getattr(module, "__all__", []) if n in set(names)]
        names = authored + [n for n in names if n not in set(authored)]
        ordered.append((module_name, module, names))
    return package, exported, ordered


def render(package_name: str, title: str, blurb: str) -> str:
    package, exported, groups = module_entries(package_name)
    out = [HEADER]
    out.append(f"# `quadrivium.{package_name}`\n")
    out.append(f"{blurb}.\n")
    guide = GUIDE_FOR.get(package_name)
    if guide:
        out.append(
            f"For worked examples and guidance on choosing between these routines, "
            f"see the [{title.lower()} guide]({guide}).\n"
        )
    out.append(
        f"**{len(exported)} public names.** Import them from the subpackage or, "
        f"where re-exported, from the top level:\n"
    )
    out.append(
        "```python\n"
        f"from quadrivium.{package_name} import {exported[0] if exported else ''}\n"
        f"import quadrivium as qd            # qd.{exported[0] if exported else ''}, "
        "if re-exported\n"
        "```\n"
    )

    out.append("## Contents\n")
    for module_name, module, names in groups:
        short = module_name.split(".")[-1]
        summary = first_line(module) or ""
        out.append(f"- [`{short}`](#{short}) &mdash; {summary.rstrip('.').lower()}"
                   f" ({len(names)})")
    out.append("")

    for module_name, module, names in groups:
        short = module_name.split(".")[-1]
        out.append(f"## `{short}`\n")
        out.append(f"<small>`{module_name}`</small>\n")
        doc = inspect.getdoc(module)
        if doc:
            paragraphs = doc.split("\n\n")
            out.append(prose(paragraphs[0]) + "\n")
            if len(paragraphs) > 1:
                out.append(prose(paragraphs[1]) + "\n")
        out.append("| Name | Signature | Summary |")
        out.append("| --- | --- | --- |")
        for name in names:
            obj = getattr(package, name)
            sig = signature_of(obj)
            marker = "*class*&nbsp;" if kind_of(obj) == "class" else ""
            sig_cell = f"`{sig}`" if sig else "&mdash;"
            out.append(f"| {marker}`{name}` | {sig_cell} | {first_line(obj)} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_index() -> str:
    out = [HEADER]
    out.append("# API reference\n")
    out.append(
        "Every public name in the library, grouped by subpackage, with its real "
        "signature and a one-line summary. These pages are generated from the "
        "installed package by `tools/gen_docs.py`, so they cannot drift from "
        "the code.\n"
    )
    out.append(
        "The narrative [guides](../guides/linalg.md) explain when to reach for "
        "which method; this reference tells you what to call.\n"
    )
    total = 0
    rows = ["| Subpackage | Public names | Covers |", "| --- | --- | --- |"]
    for name, title, blurb in SUBPACKAGES:
        _, exported, _ = module_entries(name)
        count = len(exported)
        total += count
        rows.append(f"| [`{name}`]({name}.md) | {count} | {blurb} |")
    rows.append(f"| **Total** | **{total}** | |")
    out.extend(rows)
    out.append("")
    out.append("## Top-level namespace\n")
    out.append(
        "`quadrivium` re-exports the routines reached for most often, so the common "
        "cases are one import away. Everything else lives in its subpackage.\n"
    )
    top = [n for n in quadrivium.__all__
           if n != "__version__"
           and not inspect.ismodule(getattr(quadrivium, n, None))]
    out.append("```text")
    line = ""
    for name in top:
        if len(line) + len(name) + 2 > 76:
            out.append(line.rstrip())
            line = ""
        line += name + ", "
    out.append(line.rstrip().rstrip(","))
    out.append("```")
    out.append("")
    out.append(
        f"That is {len(top)} names at the top level out of {total} public names in "
        "total.\n"
    )
    return "\n".join(out).rstrip() + "\n"


def render_changelog() -> str:
    """The root changelog, copied where MkDocs can reach it."""
    body = CHANGELOG.read_text(encoding="utf-8").rstrip()
    return f"{CHANGELOG_HEADER}\n{body}\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the checked-in pages match the code")
    args = parser.parse_args()

    pages = {API_DIR / "index.md": render_index(),
             DOCS_DIR / "changelog.md": render_changelog()}
    for name, title, blurb in SUBPACKAGES:
        pages[API_DIR / f"{name}.md"] = render(name, title, blurb)

    if args.check:
        stale = []
        for path, content in pages.items():
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT))
        if stale:
            print("Stale generated pages: "
                  + ", ".join(str(p) for p in sorted(stale)), file=sys.stderr)
            print("Run: python tools/gen_docs.py", file=sys.stderr)
            return 1
        print(f"{len(pages)} generated documentation pages are up to date.")
        return 0

    API_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in pages.items():
        path.write_text(content, encoding="utf-8")
    print(f"Wrote {len(pages)} pages under {DOCS_DIR.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
