#!/usr/bin/env python3
"""Generate the documentation pages that are derived from the source tree.

Two things here are not written by hand:

* ``docs/api/*.md`` -- the API reference. It documents every exported name in the method subpackages,
  complete signatures, source docstrings, and public class methods.
* ``docs/changelog.md`` -- a copy of the top-level ``CHANGELOG.md``, which
  MkDocs cannot read from outside its ``docs`` directory.

``tests/test_docs.py`` runs the check mode, so a stale page fails the suite.

Usage::

    python tools/gen_docs.py            # rewrite the generated pages
    python tools/gen_docs.py --check    # exit 1 if any page is stale
"""

from __future__ import annotations

import argparse
import inspect
from functools import lru_cache
import pprint
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import quadrivium  # noqa: E402

DOCS_DIR = ROOT / "docs"
API_DIR = DOCS_DIR / "api"
CHANGELOG = ROOT / "CHANGELOG.md"

# Subpackage -> (title, one-line description used on the index page).
SUBPACKAGES = [
    ("core", "Core", "Result records, exceptions, norms, and shared numerical helpers"),
    ("linalg", "Linear algebra",
     "Factorizations, eigenvalues, Krylov solvers, least squares, sparse storage, "
     "matrix functions and equations, randomized methods"),
    ("rootfind", "Root finding",
     "Scalar equations, nonlinear systems, and polynomial roots"),
    ("interpolate", "Interpolation",
     "Polynomial, spline, rational, and multivariate interpolation"),
    ("approx", "Approximation",
     "Orthogonal polynomials, Gauss nodes, least squares, Pade, minimax, Fourier"),
    ("diff", "Differentiation",
     "Finite differences, automatic differentiation, spectral differentiation"),
    ("integrate", "Integration",
     "Newton-Cotes, Gauss, adaptive, Monte Carlo, oscillatory, singular, and "
     "multidimensional quadrature"),
    ("ode", "Ordinary differential equations",
     "One-step, multistep, symplectic, exponential, extrapolation, events, BVPs, "
     "DAEs, delay equations"),
    ("pde", "Partial differential equations",
     "Parabolic, hyperbolic, elliptic, multigrid, FEM, FVM, spectral, WENO, "
     "incompressible Navier-Stokes"),
    ("optimize", "Optimization",
     "Line searches, quasi-Newton, trust region, derivative-free, global, "
     "constrained, proximal, linear programming"),
    ("transforms", "Transforms",
     "DFT/FFT family, signal processing, wavelets"),
    ("stochastic", "Stochastic methods",
     "Random generation, sampling, MCMC, statistics, SDE solvers"),
    ("special", "Special functions",
     "Gamma, beta, error, Bessel, Airy, elliptic, hypergeometric, Lambert W, "
     "zeta, spherical harmonics"),
]

GUIDE_FOR = {name: f"../guides/{name}.md" for name, _, _ in SUBPACKAGES}

# Docstrings use a little Sphinx-flavoured markup; Markdown wants plain code.
RST_ROLE = re.compile(r":(mod|func|class|meth|attr|data|obj|ref):`([^`]+)`")

# A quoted annotation, in the two places one can appear: ``x: 'int'`` and
# ``-> 'int'``.  A default value's own quotes (``method: 'str' = 'brent'``)
# follow ``=`` and are left alone.
ANNOTATION = re.compile(r"(: |-> )'([^']*)'")

HEADER = (
    "<!-- Generated by tools/gen_docs.py. Do not edit by hand;\n"
    "     run `python tools/gen_docs.py` after changing the public API. -->\n"
)

CHANGELOG_HEADER = (
    "<!-- Generated by tools/gen_docs.py from CHANGELOG.md at the repository\n"
    "     root. Edit that file, then run `python tools/gen_docs.py`. -->\n"
)


def prose(text: str) -> str:
    """Collapse a docstring paragraph to one line of Markdown."""
    return RST_ROLE.sub(r"``\2``", " ".join(text.split()))


def source_documentation(obj) -> str:
    """Avoid repeating dataclasses' automatically synthesized signature prose."""
    doc = inspect.getdoc(obj) or ""
    if (inspect.isclass(obj) and hasattr(obj, "__dataclass_fields__")
            and doc.startswith(obj.__name__ + "(")):
        return "Dataclass record storing the fields listed in its constructor signature."
    return doc


def first_line(obj) -> str:
    """Summary paragraph of an object's docstring, collapsed onto one line."""
    doc = source_documentation(obj)
    # A plain value (a constant, say) inherits its type's docstring, which
    # describes ``float``, not the constant. Show the value instead.
    if kind_of(obj) == "value" and doc == (inspect.getdoc(type(obj)) or ""):
        if isinstance(obj, dict):
            keys = ", ".join(f"`{key}`" for key in list(obj)[:6])
            suffix = ", ..." if len(obj) > 6 else ""
            return f"Dictionary with {len(obj)} entries: {keys}{suffix}."
        value = repr(obj)
        if len(value) > 190:
            value = value[:187] + "..."
        return f"`{value}`".replace("|", r"\|")
    if not doc:
        return ""
    paragraph = doc.split("\n\n")[0]
    line = " ".join(part.strip() for part in paragraph.splitlines() if part.strip())
    line = prose(line)
    if len(line) > 200:  # keep the table scannable
        line = line[:197].rsplit(" ", 1)[0] + " ..."
    return line.replace("|", r"\|")


def signature_of(obj) -> str:
    """Rendered call signature, or an empty string when there is none to show."""
    target = obj
    if inspect.isclass(obj):
        init = getattr(obj, "__init__", None)
        dataclass_fields = getattr(obj, "__dataclass_fields__", None)
        if init is None and dataclass_fields is None:
            return "()"
        target = obj
    try:
        sig_obj = inspect.signature(target)
    except (TypeError, ValueError):
        return ""
    sig = str(_name_callable_defaults(sig_obj, obj))
    # The package uses ``from __future__ import annotations``, so annotations
    # arrive as their own source text and ``str(signature)`` quotes them:
    # ``tol: 'float'``.  Unquoting is all that is needed, and it keeps the
    # output identical on every interpreter -- evaluating the annotations
    # instead would render ``Optional[float]`` as ``typing.Optional[float]``
    # before Python 3.14 and ``float | None`` from 3.14 on, so the generated
    # pages would depend on the version that generated them.
    sig = ANNOTATION.sub(r"\1\2", sig)
    sig = " ".join(sig.split())
    return sig


class _Named:
    """Stand-in whose ``repr`` is a bare name, for callable default values."""

    def __init__(self, name: str) -> None:
        self._name = name

    def __repr__(self) -> str:
        return self._name


def _name_callable_defaults(sig: inspect.Signature, obj=None) -> inspect.Signature:
    """Render ``method=brent`` instead of ``method=<function brent at 0x...>``.

    The address in the default repr changes every run, which would make the
    generated pages differ from one another for no reason.
    """
    params = []
    for param in sig.parameters.values():
        default = param.default
        if default is not inspect.Parameter.empty and callable(default):
            name = getattr(default, "__name__", None)
            if name:
                param = param.replace(default=_Named(name))
        elif type(default) is object:
            # Optional arguments sometimes use an object() sentinel so that
            # omitting the argument differs from explicitly passing None.
            # Its repr contains a process-specific address. Prefer the name
            # used in the defining module and never expose that address.
            module = inspect.getmodule(obj) if obj is not None else None
            names = [name for name, value in vars(module).items()
                     if value is default] if module is not None else []
            name = sorted(names)[0] if names else "<omitted>"
            param = param.replace(default=_Named(name))
        params.append(param)
    return sig.replace(parameters=params)


def kind_of(obj) -> str:
    if inspect.isclass(obj):
        return "class"
    if inspect.isfunction(obj) or inspect.isbuiltin(obj):
        return "function"
    return "value"


def origin_of(package, package_name: str, name: str, obj) -> str:
    """Module a name comes from, including for constants with no ``__module__``."""
    module_name = getattr(obj, "__module__", None)
    if module_name:
        return module_name
    prefix = f"quadrivium.{package_name}."
    for candidate, module in sorted(sys.modules.items()):
        if not candidate.startswith(prefix):
            continue
        if name in getattr(module, "__all__", []) and getattr(module, name, None) is obj:
            return candidate
    return f"quadrivium.{package_name}"


def module_entries(package_name: str):
    """Public names of a subpackage, grouped by the module that defines them."""
    package = getattr(quadrivium, package_name)
    exported = [n for n in getattr(package, "__all__", [])
                if not inspect.ismodule(getattr(package, n, None))]
    groups: dict[str, list[str]] = {}
    for name in exported:
        obj = getattr(package, name, None)
        if obj is None:
            continue
        groups.setdefault(origin_of(package, package_name, name, obj), []).append(name)

    ordered = []
    for module_name in sorted(groups, key=lambda m: (not m.startswith(
            f"quadrivium.{package_name}"), m)):
        try:
            module = sys.modules[module_name]
        except KeyError:  # pragma: no cover - every origin is imported already
            continue
        names = groups[module_name]
        authored = [n for n in getattr(module, "__all__", []) if n in set(names)]
        names = authored + [n for n in names if n not in set(authored)]
        ordered.append((module_name, module, names))
    return package, exported, ordered


def doc_markdown(obj) -> str:
    """Preserve complete source documentation with readable Markdown sections.

    NumPy-style parameter blocks become definition lists. Example prompts are
    fenced to keep their indentation and output, while section underlines are
    converted rather than accidentally becoming Markdown headings.
    """
    doc = source_documentation(obj)
    doc = RST_ROLE.sub(r"`\2`", doc).replace("``", "`")
    lines = doc.splitlines()
    out, index, section = [], 0, ""
    fields = {"Parameters", "Returns", "Yields", "Raises", "Attributes"}
    while index < len(lines):
        line = lines[index]
        if (index + 1 < len(lines) and line.strip()
                and re.fullmatch(r"[-=]{3,}", lines[index + 1].strip())):
            section = line.strip()
            out.extend(["", f"**{section}**", ""])
            index += 2
            continue
        if line.lstrip().startswith(">>>"):
            block = []
            while index < len(lines) and lines[index].strip():
                block.append(lines[index])
                index += 1
            out.extend(["", "```pycon", *block, "```", ""])
            continue
        if section in fields and line and not line[0].isspace():
            label = line.strip().replace("`", "")
            description = []
            index += 1
            while index < len(lines) and (not lines[index].strip()
                                          or lines[index][0].isspace()):
                description.append(lines[index].strip())
                index += 1
            out.extend([f"`{label}`", f":   {' '.join(description).strip()}", ""])
            continue
        out.append(line)
        index += 1
    return "\n".join(out).strip()


def signature_block(name, obj) -> str:
    """Show every parameter, wrapping long signatures by parameter boundary."""
    sig = signature_of(obj)
    if not sig:
        return ""
    call = name + sig
    if len(call) > 88:
        try:
            raw = _name_callable_defaults(inspect.signature(obj), obj)
            params = []
            positional_only = [p for p in raw.parameters.values()
                               if p.kind == p.POSITIONAL_ONLY]
            has_star = False
            for param in raw.parameters.values():
                if param.kind == param.KEYWORD_ONLY and not has_star:
                    params.append("*")
                    has_star = True
                if param.kind == param.VAR_POSITIONAL:
                    has_star = True
                params.append(ANNOTATION.sub(r"\1\2", str(param)))
                if positional_only and param is positional_only[-1]:
                    params.append("/")
            tail = sig[sig.rfind(")") + 1:]
            call = name + "(\n" + "\n".join("    " + p + "," for p in params) + "\n)" + tail
        except (ValueError, TypeError):
            pass
    return f"```python\n{call}\n```\n"


def api_anchor(name: str) -> str:
    """Keep case so distinct exports such as sobol and Sobol never collide."""
    return "api-" + name


@lru_cache(maxsize=1)
def class_targets():
    """Locate exported classes once for base-class cross references."""
    targets = {}
    for package_name, _, _ in SUBPACKAGES:
        package = getattr(quadrivium, package_name)
        for name in package.__all__:
            obj = getattr(package, name)
            if inspect.isclass(obj):
                targets.setdefault(obj, (package_name, name))
    return targets


def class_reference(cls):
    target = class_targets().get(cls)
    if target:
        package, name = target
        return f"[`{name}`]({package}.md#{api_anchor(name)})"
    if cls.__module__.startswith(("quadrivium._qnp", "quadrivium.numeric")):
        return "[`numeric.ndarray`](../guides/numeric.md)"
    return f"`{cls.__name__}`"


# Numeric operators and container protocols are public behavior even though
# Python spells them with underscores. Initialization already has its own
# constructor signature; interpreter plumbing and repr hooks add no guidance.
PUBLIC_PROTOCOLS = {
    "__call__", "__getitem__", "__setitem__", "__iter__", "__len__",
    "__float__", "__add__", "__radd__", "__sub__", "__rsub__", "__mul__",
    "__rmul__", "__truediv__", "__rtruediv__", "__matmul__", "__rmatmul__",
    "__neg__", "__abs__", "__pow__", "__rpow__",
}


def class_members(cls):
    """Yield each public method/property once, resolving overrides by MRO.

    Include Python implementations inherited from package base classes, but
    do not duplicate the entire native ndarray interface on Chain's page.
    """
    seen = set()
    for owner in cls.__mro__:
        module = owner.__module__
        if owner is not cls and (not module.startswith("quadrivium.")
                                 or module.startswith(("quadrivium._qnp", "quadrivium.numeric"))):
            continue
        for name, raw in owner.__dict__.items():
            if name in seen:
                continue
            seen.add(name)
            if name.startswith("_") and name not in PUBLIC_PROTOCOLS:
                continue
            member = getattr(cls, name, None)
            if isinstance(raw, property) or inspect.isroutine(member):
                yield name, raw, owner


def render(package_name: str, title: str, blurb: str) -> str:
    package, exported, groups = module_entries(package_name)
    out = [HEADER]
    out.append(f"# `quadrivium.{package_name}`\n")
    out.append(f"{blurb}.\n")
    guide = GUIDE_FOR.get(package_name)
    if guide:
        out.append(
            f"For worked examples and guidance on choosing between these routines, "
            f"see the [{title.lower()} guide]({guide}).\n"
        )
    out.append(
        f"**{len(exported)} public names.** Import them from the subpackage or, "
        f"where re-exported, from the top level:\n"
    )
    out.append("```python\n" + f"from quadrivium import {package_name}\n" + "```\n")
    out.append("Each entry includes the complete call signature and available source "
               "documentation. Class entries also list public methods and properties "
               "including inherited interfaces implemented by Quadrivium. Base-class "
               "links identify shared contracts. Keyword support differs between methods; "
               "check the specific entry before passing dispatcher options.\n")

    out.append("## Contents\n")
    for module_name, module, names in groups:
        short = module_name.split(".")[-1]
        summary = first_line(module) or ""
        out.append(f"- [`{short}`](#{short}) &mdash; {summary.rstrip('.').lower()}"
                   f" ({len(names)})")
    out.append("")

    for module_name, module, names in groups:
        short = module_name.split(".")[-1]
        out.append(f"## `{short}`\n")
        out.append(f"<small>`{module_name}`</small>\n")
        doc = inspect.getdoc(module)
        if doc:
            paragraphs = doc.split("\n\n")
            out.append(prose(paragraphs[0]) + "\n")
            if len(paragraphs) > 1:
                out.append(prose(paragraphs[1]) + "\n")
        out.append("| Name | Kind | Purpose |")
        out.append("| --- | --- | --- |")
        for name in names:
            obj = getattr(package, name)
            out.append(f"| [`{name}`](#{api_anchor(name)}) | {kind_of(obj)} | {first_line(obj)} |")
        out.append("")
        for name in names:
            obj = getattr(package, name)
            out.append(f"### `{name}` {{#{api_anchor(name)}}}\n")
            if kind_of(obj) == "value":
                out.append("```python\n" + pprint.pformat(obj, width=88, sort_dicts=False) + "\n```\n")
                continue
            out.append(signature_block(name, obj))
            out.append(doc_markdown(obj) + "\n")
            if inspect.isclass(obj):
                bases = [class_reference(base) for base in obj.__bases__
                         if base is not object]
                if bases:
                    out.append("Base classes: " + ", ".join(bases) + ".\n")
                for member_name, raw, owner in class_members(obj):
                    member = getattr(obj, member_name, None)
                    out.append(f"#### `{name}.{member_name}` "
                               f"{{#{api_anchor(name + '.' + member_name)}}}\n")
                    if owner is not obj:
                        out.append(f"Inherited from {class_reference(owner)}.\n")
                    if isinstance(raw, property):
                        out.append("Read-only property.\n" if raw.fset is None else "Property.\n")
                        documentation = doc_markdown(raw)
                    else:
                        out.append(signature_block(f"{name}.{member_name}", member))
                        documentation = doc_markdown(member)
                    if documentation:
                        out.append(documentation + "\n")
    return "\n".join(out).rstrip() + "\n"


def render_index() -> str:
    out = [HEADER]
    out.append("# API reference\n")
    out.append(
        "Every exported name in the numerical-method subpackages, with its real "
        "complete signature, source documentation, and public class methods. "
        "These pages are generated from this checkout by `tools/gen_docs.py`. "
        "The generation check catches changes to exports, defaults, and docstrings; "
        "the guides explain the numerical assumptions behind the calls.\n"
    )
    out.append(
        "The narrative [guides](../guides/linalg.md) explain when to reach for "
        "which method; this reference tells you what to call.\n"
    )
    out.append("## How to read an entry\n")
    out.append("A signature without `*` accepts ordinary positional arguments; "
               "arguments after `*` are keyword-only. `None` often requests an "
               "automatic choice, but its meaning is method-specific. A `**kwargs` "
               "parameter forwards options to a selected implementation. Missing "
               "return annotations do not imply that a routine returns `None`. In "
               "class method signatures, `self` denotes the instance. An uppercase "
               "private default such as `_UNSET` is an internal omission sentinel, "
               "and `<factory>` creates a fresh dataclass default; callers normally "
               "omit these arguments rather than importing the placeholder.\n")
    out.append("Some routines return an array or scalar; others return a record "
               "with status and diagnostics. Read [result contracts](../getting-started.md#result-records) "
               "before interpreting tolerances or convergence flags. The "
               "[array guide](../guides/numeric.md) documents `quadrivium.numeric`, "
               "whose C-backed primitives are separate from the method catalogue below.\n")
    out.append("## Subpackages\n")
    total = 0
    rows = ["| Subpackage | Public names | Covers |", "| --- | --- | --- |"]
    for name, title, blurb in SUBPACKAGES:
        _, exported, _ = module_entries(name)
        count = len(exported)
        total += count
        rows.append(f"| [`{name}`]({name}.md) | {count} | {blurb} |")
    rows.append(f"| **Total** | **{total}** | |")
    out.extend(rows)
    out.append("")
    out.append("## Top-level namespace\n")
    out.append(
        "`quadrivium` re-exports the routines reached for most often, so the common "
        "cases are one import away. Everything else lives in its subpackage.\n"
    )
    top = [n for n in quadrivium.__all__
           if n != "__version__"
           and not inspect.ismodule(getattr(quadrivium, n, None))]
    out.append("```text")
    line = ""
    for name in top:
        if len(line) + len(name) + 2 > 76:
            out.append(line.rstrip())
            line = ""
        line += name + ", "
    out.append(line.rstrip().rstrip(","))
    out.append("```")
    out.append("")
    out.append(
        f"That is {len(top)} names at the top level out of {total} exported names "
        "in the method catalogue.\n"
    )
    return "\n".join(out).rstrip() + "\n"


def render_changelog() -> str:
    """The root changelog, copied where MkDocs can reach it."""
    body = CHANGELOG.read_text(encoding="utf-8").rstrip()
    return f"{CHANGELOG_HEADER}\n{body}\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the checked-in pages match the code")
    args = parser.parse_args()

    pages = {API_DIR / "index.md": render_index(),
             DOCS_DIR / "changelog.md": render_changelog()}
    for name, title, blurb in SUBPACKAGES:
        pages[API_DIR / f"{name}.md"] = render(name, title, blurb)

    if args.check:
        stale = []
        for path, content in pages.items():
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT))
        if stale:
            print("Stale generated pages: "
                  + ", ".join(str(p) for p in sorted(stale)), file=sys.stderr)
            print("Run: python tools/gen_docs.py", file=sys.stderr)
            return 1
        print(f"{len(pages)} generated documentation pages are up to date.")
        return 0

    API_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in pages.items():
        path.write_text(content, encoding="utf-8")
    print(f"Wrote {len(pages)} pages under {DOCS_DIR.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
